#!/usr/bin/env python3
"""
Builds dist/map.html - the whole API map as one self-contained file.

Why this exists: a page opened from disk cannot load its own files. The browser
refuses ES module scripts and fetch() from origin 'null', so index.html renders
blank when double-clicked. Inlining everything sidesteps both.

What survives the trip: the live explorer. Access-Control-Allow-Origin: * accepts
origin 'null', so the browser-callable APIs answer a file:// page exactly as they
answer the hosted one (probed - data.gov.il, CBS and Open Bus all return 200 from
file://; Knesset still fails on CORS, as it should). The offline copy is the
whole thing, not a degraded preview.

The site itself is untouched and still has no build step. Only this extra
artifact is generated.

Usage:
    ./tools/bundle.py           write dist/map.html
    ./tools/bundle.py --check   exit non-zero if dist/map.html is stale
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "dist" / "map.html"
SITE = "https://agmonr.github.io/govapiportal"

# Dependency order. These are first-party and each has exactly one import edge,
# which is what makes flattening them safe.
SOURCES = ["src/ui.js", "src/explorer.js", "src/map.js"]

IMPORT_RE = re.compile(r"^\s*import\s.*?;\s*$", re.M)
EXPORT_RE = re.compile(r"^export\s+", re.M)
# Anything left after stripping means an assumption above has broken.
LEFTOVER_RE = re.compile(r"^\s*(?:import\s|export\s)", re.M)


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def flatten(rel: str) -> str:
    """Strip module syntax so several files can share one inline module scope."""
    src = IMPORT_RE.sub("", read(rel))
    src = EXPORT_RE.sub("", src)
    if LEFTOVER_RE.search(src):
        bad = LEFTOVER_RE.search(src).group(0).strip()
        sys.exit(f"error: {rel} still has module syntax after stripping: {bad!r}\n"
                 f"       bundle.py flattens files into one scope and cannot keep it.")
    return src


def build() -> str:
    html = read("index.html")
    data = json.loads(read("apis.json"))  # parse to validate, not just to embed

    # </script> inside the data would close the tag early. JSON has no business
    # containing one, but the cost of being wrong here is a silently broken file.
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")

    # Inline the stylesheet.
    css = "<style>\n" + read("src/style.css").strip() + "\n</style>"
    html, n = re.subn(
        r'<link rel="stylesheet" href="\./src/style\.css">',
        lambda _m: css,
        html,
    )
    if n != 1:
        sys.exit("error: stylesheet <link> not found in index.html - bundler is out of date")

    # The file:// notice and its guard are about *this* limitation. In the
    # bundle the limitation does not exist, so showing either would be a lie.
    html, n = re.subn(r"\n\s*<!--\n\s*Opened by double-clicking.*?</script>\n", "\n", html, flags=re.S)
    if n != 1:
        sys.exit("error: file:// guard block not found in index.html - bundler is out of date")
    html, n = re.subn(r'\s*<div id="fileproto".*?</div>\n\n', "\n", html, flags=re.S)
    if n != 1:
        sys.exit("error: #fileproto notice not found in index.html - bundler is out of date")

    # Relative links leave the repo when this file does. Someone who downloads
    # map.html has no ./plans.html next to it, so point at the hosted copy.
    html, n = re.subn(r'href="\./plans\.html"',
                      lambda _m: f'href="{SITE}/plans.html"', html)
    if n != 1:
        sys.exit("error: plans.html link not found in index.html - bundler is out of date")

    # Replace the module <script> with data + flattened sources. Inline modules
    # are exempt from the origin-'null' block (verified in headless Chromium),
    # so type="module" is kept and the sources need no further rewriting.
    bundled = "\n".join(flatten(s) for s in SOURCES)
    script = (
        '<script type="module">\n'
        "// Generated by tools/bundle.py - edit src/ and apis.json, then regenerate.\n"
        f"globalThis.__API_DATA__ = {payload};\n\n"
        f"{bundled}\n"
        "</script>"
    )
    html, n = re.subn(r'<script type="module" src="\./src/map\.js"></script>',
                      lambda _m: script, html)
    if n != 1:
        sys.exit("error: module <script> not found in index.html - bundler is out of date")

    note = ("<!--\n  Self-contained build of the Israeli government API map.\n"
            "  Generated by tools/bundle.py from apis.json + src/ - do not edit by hand.\n"
            f"  Data probed: {data['probed']} | {len(data['apis'])} APIs across "
            f"{len(data['portals'])} portals.\n-->\n")
    return note + html


def main() -> int:
    html = build()
    check = "--check" in sys.argv[1:]

    if check:
        if not OUT.exists():
            print(f"STALE: {OUT.relative_to(ROOT)} does not exist. Run ./tools/bundle.py")
            return 1
        if OUT.read_text(encoding="utf-8") != html:
            print(f"STALE: {OUT.relative_to(ROOT)} does not match apis.json + src/. "
                  "Run ./tools/bundle.py")
            return 1
        print(f"ok: {OUT.relative_to(ROOT)} is in sync with apis.json + src/")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(html.encode('utf-8')) / 1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
