#!/usr/bin/env python3
"""
Builds the public/private canopy split: for each city and neighborhood, how
much of its already-computed total tree canopy (see canopy_build.py) sits
inside the real, unioned street-buffer area ("public" - a proper geometric
union of every street's 7.5m buffer, intersected with the city/neighborhood
boundary) versus everywhere else ("private" - by subtraction).

This does real spatial geometry against the local canopy GeoPackage - the
same rigor canopy_build.py itself uses for city/neighborhood/street canopy -
rather than summing STREET_CANOPY's already-computed per-street numbers,
which has two problems a proper union avoids: (1) two streets whose buffers
overlap at an intersection would each count that overlap once in a sum -
canopy_area_within on the true UNION counts it once; (2) a neighborhood-level
sum relying on each street's centroid-based "nb" attribution misses any
street whose centroid didn't resolve to a neighborhood - a direct geometric
intersection test between a neighborhood polygon and every candidate street
buffer has no such gap.

City-level: for each city, union every street buffer attributed to it (by
canopy_build.py's own street_geoms() grouping), intersect with the city
boundary, then canopy_area_within() that intersection - same function
canopy_build.py's build_cities()/build_neighborhoods() already use.

Neighborhood-level: for each neighborhood, find every street buffer (from
its own city, via a per-city STRtree) that actually intersects the
neighborhood polygon - not by label, by geometry - union those, intersect
with the neighborhood polygon, then canopy_area_within() that.

Usage:
    python3 tools/canopy_split_build.py
"""
import json
import sys
import time
from pathlib import Path

from osgeo import ogr
ogr.UseExceptions()

sys.path.insert(0, str(Path(__file__).resolve().parent))
from canopy_build import (
    load_muni_geoms, city_index, neighborhood_geoms, street_geoms,
    open_canopy, canopy_area_within, write_js as _unused_write_js,
)

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def write_js(varname, data, out_path, header_comment):
    out_path.write_text(
        f"// {header_comment}\n"
        f"// Generated by tools/canopy_split_build.py - do not edit by hand.\n"
        f"export const {varname} = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    kb = out_path.stat().st_size / 1024
    log(f"wrote {out_path.relative_to(ROOT)} ({kb:.1f} KB)")


def build():
    from shapely.ops import unary_union
    from shapely.strtree import STRtree
    import shapely.wkt as swkt

    log("loading city boundaries...")
    munis_all = load_muni_geoms()
    munis_all = {k: v for k, v in munis_all.items() if not k.startswith("ללא שיפוט")}
    names, shapes, tree = city_index(munis_all)
    city_shape_by_name = dict(zip(names, shapes))

    munis = {k: v for k, v in munis_all.items() if v[2] != "מועצה אזורית"}
    log(f"{len(munis)} cities (regional councils excluded)")

    log("loading street buffers...")
    street_list = street_geoms(names, shapes, tree)  # (city, name, shapely buf, length_m, nb)

    bufs_by_city = {}
    for city, _name, buf, _len, _nb in street_list:
        bufs_by_city.setdefault(city, []).append(buf)
    log(f"streets grouped into {len(bufs_by_city)} cities")

    trees_by_city = {city: STRtree(bufs) for city, bufs in bufs_by_city.items()}

    log("loading neighborhood boundaries...")
    nb_list = neighborhood_geoms(names, shapes, tree)  # (city, name, shapely geom, approx)

    ds, canopy = open_canopy()

    def public_area_for(city, geom_shp):
        """canopy area within `geom_shp` (shapely) that also falls inside the
        union of `city`'s street buffers - 0.0 if the city has no streets or
        none reach this geometry at all."""
        bufs = bufs_by_city.get(city)
        if not bufs:
            return 0.0
        candidate_idx = trees_by_city[city].query(geom_shp)
        candidates = [bufs[i] for i in candidate_idx if bufs[i].intersects(geom_shp)]
        if not candidates:
            return 0.0
        public_shape = unary_union(candidates).intersection(geom_shp)
        if public_shape.is_empty:
            return 0.0
        public_ogr = ogr.CreateGeometryFromWkt(public_shape.wkt)
        area, _n = canopy_area_within(canopy, public_ogr)
        return area

    log("computing city-level public/private split...")
    city_out = {}
    t0 = time.time()
    for i, (name, (geom_ogr, _code, _sug)) in enumerate(munis.items()):
        area = geom_ogr.GetArea()
        if not area:
            continue
        total_area, _n = canopy_area_within(canopy, geom_ogr)
        public_area = min(public_area_for(name, city_shape_by_name[name]), total_area)
        private_area = total_area - public_area
        city_out[name] = {
            "areaM2": round(area, 1),
            "totalPct": round(100 * total_area / area, 2),
            "publicPct": round(100 * public_area / area, 2),
            "privatePct": round(100 * private_area / area, 2),
            "totalM2": round(total_area, 1), "publicM2": round(public_area, 1), "privateM2": round(private_area, 1),
        }
        if (i + 1) % 25 == 0:
            elapsed = time.time() - t0
            log(f"  {i+1}/{len(munis)} cities, {elapsed:.0f}s elapsed, ~{elapsed/(i+1)*len(munis):.0f}s total est.")
    log(f"cities done in {time.time()-t0:.0f}s")

    log("computing neighborhood-level public/private split...")
    nb_out = {}
    t0 = time.time()
    for i, (city, name, geom_shp, approx) in enumerate(nb_list):
        geom_ogr = ogr.CreateGeometryFromWkt(geom_shp.wkt)
        area = geom_ogr.GetArea()
        if not area:
            continue
        total_area, _n = canopy_area_within(canopy, geom_ogr)
        public_area = min(public_area_for(city, geom_shp), total_area) if city else 0.0
        private_area = total_area - public_area
        key = f"{city or '—'}::{name}"
        entry = {
            "areaM2": round(area, 1),
            "totalPct": round(100 * total_area / area, 2),
            "publicPct": round(100 * public_area / area, 2),
            "privatePct": round(100 * private_area / area, 2),
            "totalM2": round(total_area, 1), "publicM2": round(public_area, 1), "privateM2": round(private_area, 1),
        }
        if approx:
            entry["approx"] = True
        nb_out[key] = entry
        if (i + 1) % 100 == 0:
            elapsed = time.time() - t0
            log(f"  {i+1}/{len(nb_list)} neighborhoods, {elapsed:.0f}s elapsed, ~{elapsed/(i+1)*len(nb_list):.0f}s total est.")
    ds = None
    log(f"neighborhoods done in {time.time()-t0:.0f}s - {len(nb_out)} total")

    return city_out, nb_out


def main():
    stamp = time.strftime("%Y-%m-%dT%H:%M%z") or time.strftime("%Y-%m-%dT%H:%M")
    city_out, nb_out = build()
    write_js("CITY_CANOPY_SPLIT", city_out, SRC / "canopy-split-cities.js",
              f"City-level public (street buffer) vs. private tree canopy split, computed {stamp}")
    write_js("NEIGHBORHOOD_CANOPY_SPLIT", nb_out, SRC / "canopy-split-neighborhoods.js",
              f"Neighborhood-level public (street buffer) vs. private tree canopy split, computed {stamp}")


if __name__ == "__main__":
    main()
