#!/usr/bin/env python3
"""
Builds the public/private canopy split: for each city and neighborhood, how
much of its already-computed total tree canopy (see canopy_build.py) sits
inside a street's 7.5m public-road buffer ("public") versus everywhere else
("private" - gardens, yards, any private lot). Pure aggregation over the
three tables canopy_build.py already produced - no shapefile access, no new
geometry work.

public canopy for a city/neighborhood = sum of canopyAreaM2 across every
STREET_CANOPY entry attributed to it. Two known approximations, same
tolerance already disclosed elsewhere on this site: (1) two streets whose
7.5m buffers overlap at an intersection each count that overlap once, a mild
double-count of "public"; (2) neighborhood-level public sums only include
streets whose centroid-based neighborhood attribution ("nb") resolved to
something - unattributed streets' canopy is invisible at the neighborhood
level (still counted at the city level, where attribution is always known -
every STREET_CANOPY key starts with its city).

private = max(0, total - public) per area, clamped for the rare case where
approximation (1) pushes the public sum slightly past the total.

Usage:
    python3 tools/canopy_split_build.py
"""
import json
import re
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"


def log(msg):
    print(msg, flush=True)


def load_export(path, varname):
    text = path.read_text(encoding="utf-8")
    m = re.search(rf"export const {varname} = (\{{.*\}});\s*$", text, re.DOTALL)
    return json.loads(m.group(1))


def build():
    cities = load_export(SRC / "tree-canopy-cities.js", "CITY_CANOPY")
    neighborhoods = load_export(SRC / "tree-canopy-neighborhoods.js", "NEIGHBORHOOD_CANOPY")
    streets = load_export(SRC / "tree-canopy-streets.js", "STREET_CANOPY")

    public_by_city = {}
    public_by_nb = {}
    for key, v in streets.items():
        city, _name = key.split("::", 1)
        public_by_city[city] = public_by_city.get(city, 0.0) + v["canopyAreaM2"]
        nb = v.get("nb")
        if nb:
            nb_key = f"{city}::{nb}"
            public_by_nb[nb_key] = public_by_nb.get(nb_key, 0.0) + v["canopyAreaM2"]

    city_out = {}
    for name, v in cities.items():
        area = v["cityAreaM2"]
        total = v["canopyAreaM2"]
        public = min(public_by_city.get(name, 0.0), total)
        private = total - public
        if not area:
            continue
        city_out[name] = {
            "areaM2": area,
            "totalPct": round(100 * total / area, 2),
            "publicPct": round(100 * public / area, 2),
            "privatePct": round(100 * private / area, 2),
            "totalM2": round(total, 1), "publicM2": round(public, 1), "privateM2": round(private, 1),
        }

    nb_out = {}
    for key, v in neighborhoods.items():
        area = v["areaM2"]
        total = v["canopyAreaM2"]
        public = min(public_by_nb.get(key, 0.0), total)
        private = total - public
        if not area:
            continue
        entry = {
            "areaM2": area,
            "totalPct": round(100 * total / area, 2),
            "publicPct": round(100 * public / area, 2),
            "privatePct": round(100 * private / area, 2),
            "totalM2": round(total, 1), "publicM2": round(public, 1), "privateM2": round(private, 1),
        }
        if key not in public_by_nb:
            entry["publicUnknown"] = True
        if v.get("approx"):
            entry["approx"] = True
        nb_out[key] = entry

    return city_out, nb_out


def write_js(varname, data, out_path, header_comment):
    out_path.write_text(
        f"// {header_comment}\n"
        f"// Generated by tools/canopy_split_build.py - do not edit by hand.\n"
        f"export const {varname} = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    kb = out_path.stat().st_size / 1024
    log(f"wrote {out_path.relative_to(ROOT)} ({kb:.1f} KB)")


def main():
    stamp = time.strftime("%Y-%m-%dT%H:%M%z") or time.strftime("%Y-%m-%dT%H:%M")
    city_out, nb_out = build()
    write_js("CITY_CANOPY_SPLIT", city_out, SRC / "canopy-split-cities.js",
              f"City-level public (street buffer) vs. private tree canopy split, computed {stamp}")
    write_js("NEIGHBORHOOD_CANOPY_SPLIT", nb_out, SRC / "canopy-split-neighborhoods.js",
              f"Neighborhood-level public (street buffer) vs. private tree canopy split, computed {stamp}")


if __name__ == "__main__":
    main()
