#!/usr/bin/env python3
"""
Regenerates src/city-stats.js: per-city accident severity for 2020-2024.

Same "snapshot fact, dated" idea as YEAR_STATS in src/accidents.js, one level
finer. The five per-year DataStore resources are aggregated by settlement here,
offline, because the SQL endpoint that would GROUP BY server-side is WAF-blocked
(datastore_search_sql returns a 403 HTML page - the same WAF probe.py documents).
So we page the raw rows (two columns only) and count locally.

Before writing anything it re-checks the national severity totals against the
numbers already baked into src/accidents.js (YEAR_STATS); a mismatch means the
source data moved and aborts rather than shipping figures that disagree with the
rest of the page. The per-city sums are what those national totals are made of,
so they inherit the same apps[].computed_at date - this script does not stamp a
date of its own.

Usage:
    ./tools/compute_cities.py            regenerate src/city-stats.js
    ./tools/compute_cities.py --check    exit 1 if the file would change
"""
import argparse
import json
import pathlib
import sys
import time
import urllib.parse
import urllib.request
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "city-stats.js"

# data - <year> resources of dataset 02789da8-7a3e-4bfc-b771-1732b1cf403c.
RESOURCES = {
    2020: "70a93f04-2ffe-4b02-a062-a818600a5b67",
    2021: "6957e7c2-6d68-4332-bbc8-2ee8d5ba6bd6",
    2022: "ede3f02a-f9aa-4a6f-9eca-4c11a06f0043",
    2023: "ae0f1679-139f-4e69-a869-a60d5d76518b",
    2024: "05d14adb-fe54-49f7-b7ce-f30348e2d959",
}
# Settlement code -> name (Population and Immigration Authority); the accidents
# resource stores only the numeric SEMEL_YISHUV.
SETTLEMENTS = "5c78e9fa-c2e2-4771-93ff-7f400a12f7ba"
BASE = "https://data.gov.il/api/3/action/datastore_search"

# HUMRAT_TEUNA: 1 fatal, 2 severe, 3 light (resource Dictionary, MS_TAVLA 4).
# National severity totals to validate the aggregation against - must equal
# YEAR_STATS in src/accidents.js.
EXPECT = {
    2024: (405, 2452, 5458), 2023: (338, 2374, 6120), 2022: (319, 2320, 7765),
    2021: (336, 2208, 9010), 2020: (286, 1899, 8651),
}
YEARS = sorted(RESOURCES)


def get(url):
    for attempt in range(5):
        try:
            with urllib.request.urlopen(url, timeout=60) as r:
                return json.load(r)
        except Exception as e:  # noqa: BLE001 - transient API/WAF hiccups, retry
            print(f"  retry {attempt}: {e}", file=sys.stderr)
            time.sleep(2)
    sys.exit(f"gave up fetching {url}")


def fetch_all(resource_id, fields):
    """Every row of a resource, paging past the 10,000-row DataStore cap."""
    rows, offset = [], 0
    while True:
        q = urllib.parse.urlencode({"resource_id": resource_id, "fields": fields,
                                    "limit": 10000, "offset": offset})
        result = get(f"{BASE}?{q}")["result"]
        rows += result["records"]
        offset += len(result["records"])
        if offset >= result["total"] or not result["records"]:
            return rows


def build():
    names = {}
    for r in fetch_all(SETTLEMENTS, "סמל_ישוב,שם_ישוב"):
        code = str(r.get("סמל_ישוב") or "").strip()
        name = str(r.get("שם_ישוב") or "").strip()
        if code:
            names[code] = name

    # code -> year -> [fatal, severe, light]
    data = defaultdict(lambda: defaultdict(lambda: [0, 0, 0]))
    for year in YEARS:
        f = s = l = 0
        for r in fetch_all(RESOURCES[year], "SEMEL_YISHUV,HUMRAT_TEUNA"):
            sev = r.get("HUMRAT_TEUNA")
            code = str(r.get("SEMEL_YISHUV") or "0").strip()
            if sev in (1, 2, 3):
                data[code][year][sev - 1] += 1
                if sev == 1: f += 1
                elif sev == 2: s += 1
                else: l += 1
        if (f, s, l) != EXPECT[year]:
            sys.exit(f"national {year} severity {(f, s, l)} != expected "
                     f"{EXPECT[year]} - source data moved; reconcile YEAR_STATS "
                     f"in src/accidents.js before regenerating.")
    return data, names


def render(data, names):
    # Every settlement with an accident and a resolvable name, busiest first,
    # so the datalist surfaces big cities as you start typing.
    def total(code):
        return sum(sum(v) for v in data[code].values())
    cities = sorted((c for c in data if c not in ("0", "") and c in names),
                    key=total, reverse=True)

    def q(text):
        return text.replace("\\", "\\\\").replace("'", "\\'")

    lines = [
        "/**",
        " * Per-city accident severity, 2020-2024 - GENERATED by tools/compute_cities.py,",
        " * do not hand-edit. Same dated snapshot as YEAR_STATS in accidents.js (its",
        " * per-city sums validate against the national totals), so it carries no date",
        " * of its own - apps[].computed_at in apis.json dates the whole set.",
        " *",
        " * Every settlement that had an accident in the period and a resolvable name",
        f" * ({len(cities)} of them), ranked most-accidents-first. Each row is packed flat",
        " * to keep the file small:",
        " *   SEMEL_YISHUV code -> [name, f20,s20,l20, f21,s21,l21, … f24,s24,l24]",
        " * where f/s/l are fatal / severe / light accident counts for that year.",
        " */",
        "export const CITY_YEARS = ["
        + ", ".join(f"'{y}'" for y in YEARS) + "];",
        "",
        "export const CITY_ROWS = {",
    ]
    for code in cities:
        nums = []
        for year in YEARS:
            nums += data[code][year]
        packed = ", ".join(str(n) for n in nums)
        lines.append(f"  '{code}': ['{q(names[code])}', {packed}],")
    lines.append("};")
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if src/city-stats.js would change")
    args = ap.parse_args()

    data, names = build()
    text = render(data, names)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is stale - run ./tools/compute_cities.py")
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return

    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
