#!/usr/bin/env python3
"""
Builds simplified city/neighborhood boundary shapes for canopy-map.html -
the only genuinely new data that page needs. All three of its layers'
VALUES already exist (see tree-canopy-cities.js, canopy-split-cities.js,
heat-cities.js and their neighborhood siblings) - this script only adds the
geometry to draw them on. Reuses canopy_build.py's own boundary-loading
functions rather than re-parsing the source JSON a second time.

Ships two coordinate systems per level: ITM/EPSG:2039 (src/map-boundaries-
*.js, loaded by default - a flat, locally-scaled view with no external
dependency) and the same shapes reprojected to WGS84/EPSG:4326
(src/map-boundaries-*-wgs84.js, loaded lazily only when a visitor opts into
the real OSM-tile basemap overlay, to align with fetched tiles). Both are
computed once here via GDAL's own accurate reprojection - mirroring
canopy_build.py's to_itm(), just the other direction - not a live API call
or a hand-rolled projection formula.

Polygons are simplified (shapely, preserve_topology=True) at a tolerance
well below city-block scale - measured directly against these same sources
this session: 186 cities + 1,283 neighborhoods combined lands around
150-300KB gzipped at 25-50m tolerance, comfortably shippable. Holes are
dropped (a choropleth only needs each region's outer silhouette to fill/
stroke/hit-test, not a donut hole invisible at this scale).

Usage:
    python3 tools/map_geo_build.py
"""
import json
import sys
import time
from pathlib import Path

from osgeo import ogr, osr
ogr.UseExceptions()

sys.path.insert(0, str(Path(__file__).resolve().parent))
from canopy_build import load_muni_geoms, city_index, neighborhood_geoms

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"

SIMPLIFY_TOLERANCE_M = 30
ITM_PRECISION = 1  # decimal places kept for ITM meters (0.1m)
WGS84_PRECISION = 6  # ~0.11m at this latitude


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def itm_to_wgs84_transform():
    src = osr.SpatialReference()
    src.ImportFromEPSG(2039)
    src.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
    dst = osr.SpatialReference()
    dst.ImportFromEPSG(4326)
    dst.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
    return osr.CoordinateTransformation(src, dst)


def simplified_rings(shapely_geom):
    """[[ [x,y], ... ], ...] - one ring per polygon part (a MultiPolygon,
    e.g. a city with exclaves, yields one entry per part), simplified and
    coordinate-rounded. Exterior ring only - see module docstring for why
    holes are dropped."""
    simplified = shapely_geom.simplify(SIMPLIFY_TOLERANCE_M, preserve_topology=True)
    geoms = simplified.geoms if simplified.geom_type == "MultiPolygon" else [simplified]
    rings = []
    for g in geoms:
        if g.is_empty or not g.exterior:
            continue
        ring = [[round(c[0], ITM_PRECISION), round(c[1], ITM_PRECISION)] for c in g.exterior.coords]
        rings.append(ring)
    return rings


def reproject_rings(rings, transform):
    out = []
    for ring in rings:
        new_ring = []
        for x, y in ring:
            result = transform.TransformPoint(x, y)
            new_ring.append([round(result[0], WGS84_PRECISION), round(result[1], WGS84_PRECISION)])
        out.append(new_ring)
    return out


def build():
    import shapely.wkt as swkt

    log("loading city boundaries...")
    munis_all = load_muni_geoms()
    munis_all = {k: v for k, v in munis_all.items() if not k.startswith("ללא שיפוט")}
    names, shapes, tree = city_index(munis_all)

    munis = {k: v for k, v in munis_all.items() if v[2] != "מועצה אזורית"}
    log(f"{len(munis)} cities (regional councils excluded)")

    transform = itm_to_wgs84_transform()

    city_out = {}
    city_out_wgs84 = {}
    for name, (geom_ogr, _code, _sug) in munis.items():
        shp = swkt.loads(geom_ogr.ExportToWkt())
        rings = simplified_rings(shp)
        if not rings:
            continue
        city_out[name] = {"rings": rings}
        city_out_wgs84[name] = {"rings": reproject_rings(rings, transform)}
    log(f"{len(city_out)} city shapes built")

    log("loading neighborhood boundaries...")
    nb_list = neighborhood_geoms(names, shapes, tree)
    nb_out = {}
    nb_out_wgs84 = {}
    for city, name, geom_shp, _approx in nb_list:
        rings = simplified_rings(geom_shp)
        if not rings:
            continue
        key = f"{city or '—'}::{name}"
        nb_out[key] = {"rings": rings}
        nb_out_wgs84[key] = {"rings": reproject_rings(rings, transform)}
    log(f"{len(nb_out)} neighborhood shapes built")

    return city_out, city_out_wgs84, nb_out, nb_out_wgs84


def write_js(varname, data, out_path, header_comment):
    out_path.write_text(
        f"// {header_comment}\n"
        f"// Generated by tools/map_geo_build.py - do not edit by hand.\n"
        f"export const {varname} = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    kb = out_path.stat().st_size / 1024
    log(f"wrote {out_path.relative_to(ROOT)} ({kb:.1f} KB)")


def main():
    stamp = time.strftime("%Y-%m-%dT%H:%M%z") or time.strftime("%Y-%m-%dT%H:%M")
    city_out, city_wgs84, nb_out, nb_wgs84 = build()
    write_js("MAP_CITIES", city_out, SRC / "map-boundaries-cities.js",
              f"Simplified city boundary shapes (ITM/EPSG:2039), computed {stamp}")
    write_js("MAP_NEIGHBORHOODS", nb_out, SRC / "map-boundaries-neighborhoods.js",
              f"Simplified neighborhood boundary shapes (ITM/EPSG:2039), computed {stamp}")
    write_js("MAP_CITIES_WGS84", city_wgs84, SRC / "map-boundaries-cities-wgs84.js",
              f"Same city shapes reprojected to WGS84/EPSG:4326 - lazily loaded only when the OSM basemap toggle is on, computed {stamp}")
    write_js("MAP_NEIGHBORHOODS_WGS84", nb_wgs84, SRC / "map-boundaries-neighborhoods-wgs84.js",
              f"Same neighborhood shapes reprojected to WGS84/EPSG:4326 - lazily loaded only when the OSM basemap toggle is on, computed {stamp}")


if __name__ == "__main__":
    main()
