#!/usr/bin/env python3
"""
Builds the real-estate price/m² comparison data: city / neighborhood median
CPI-adjusted price per square meter, from the local (gitignored) raw deal
dump already fetched from GovMap's real-estate API (zip/real_estate_deals_raw.jsonl,
~285k deals nationwide since 2021-08) plus the same municipal/OSM-neighborhood
boundaries canopy_build.py already resolved (zip/muni_il.json, zip/osm_neighborhoods_raw.json,
zip/osm_neighborhood_points.json) - reuses load_muni_geoms()/city_index()/
find_city()/neighborhood_geoms() as-is, no new boundary geometry.

Each deal is assigned to a city/neighborhood by point-in-polygon on its own
centroid (same simplification canopy_build.py uses for tree canopy - a deal's
polygon is a single building footprint, tiny next to a city/neighborhood, so
centroid vs. true-intersection makes no practical difference here).

Usage:
    python3 tools/real_estate_build.py
"""
import json
import re
import sys
import time
from pathlib import Path

from osgeo import ogr
ogr.UseExceptions()

sys.path.insert(0, str(Path(__file__).resolve().parent))
from canopy_build import load_muni_geoms, city_index, find_city, neighborhood_geoms

ROOT = Path(__file__).resolve().parent.parent
ZIP = ROOT / "zip"
SRC = ROOT / "src"
DEALS_OUT_DIR = ROOT / "assets" / "deals"

DEALS_FILE = ZIP / "real_estate_deals_raw.jsonl"
CPI_FILE = ZIP / "cpi_table.json"
STATS_EXCLUDE_TYPES = {"קרקע", "מגרש", "משק חקלאי", "משק עזר"}  # kept out of city/neighborhood price/sqm stats - land price/sqm isn't comparable to built-property price/sqm - but (unlike before) still shown in the individual-deals list, see PLOT_TYPES
MIN_PRICE_SQM = 2000
MAX_PRICE_SQM = 150000
MIN_SAMPLES_CITY = 5
MIN_SAMPLES_NB = 5

# Deal types where "how big is MY plot" is a meaningful question, so we attach
# a "pa" (plot area m^2, from the deal's own גוש/חלקה polygon - see
# plot_area_sqm()) - and, when that polygon is shared with other registered
# sub-parcels, a "pu" (how many). Ordinary apartment types are excluded - an
# apartment owner's fractional share of the building's land isn't "their
# plot" the way a house's registered parcel is.
PLOT_TYPES = {
    "חד משפחתי (וילה)", "קוטג' חד משפחתי", "קוטג' דו משפחתי", "בנין",
    "קרקע", "מגרש", "משק חקלאי", "משק עזר", "עסק", "אחר",
}

CENTROID_RE = re.compile(r"(-?\d+\.?\d*)\s+(-?\d+\.?\d*)")


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def write_js(varname, data, out_path, header_comment):
    out_path.write_text(
        f"// {header_comment}\n"
        f"// Generated by tools/real_estate_build.py - do not edit by hand.\n"
        f"export const {varname} = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    kb = out_path.stat().st_size / 1024
    log(f"wrote {out_path.relative_to(ROOT)} ({kb:.1f} KB)")


def polygon_centroid_3857(shape):
    inner = shape.split("(((")[1].split(")))")[0]
    pts = CENTROID_RE.findall(inner)
    if not pts:
        return None
    xs = [float(p[0]) for p in pts]
    ys = [float(p[1]) for p in pts]
    return sum(xs) / len(xs), sum(ys) / len(ys)


_plot_area_cache = {}  # polygonId (or raw shape, if that's missing) -> area m^2 - many PLOT_TYPES deals
                        # (esp. multiple units of the same "בנין") repeat the identical shape string


def plot_area_sqm(shape, poly_id, transformer):
    """Area (m^2) of the deal's own גוש/חלקה polygon, reprojected to ITM
    (EPSG:2039, effectively equal-area for a country this narrow). This is the
    physical land parcel the deal's shape traces - not the built/asset area
    (see PLOT_TYPES) - so it's what answers "how big is the plot", not "how
    big is the unit"."""
    cache_key = poly_id or shape
    if cache_key in _plot_area_cache:
        return _plot_area_cache[cache_key]
    from shapely import wkt as shapely_wkt
    from shapely.ops import transform as shapely_transform
    try:
        poly_itm = shapely_transform(transformer.transform, shapely_wkt.loads(shape))
        area = poly_itm.area
    except Exception:
        area = None
    _plot_area_cache[cache_key] = area
    return area


def load_deals(transformer):
    """Yields (x_3857, y_3857, adj_price_per_sqm, raw) for every deal that
    passes the same filters build_heatmap.py (the earlier national-heatmap
    pass) used, so the two views stay numerically consistent. `raw` carries
    the handful of fields the per-city deal-list files (see write_deal_files
    below) actually display - deliberately NOT the CPI-adjusted price: the
    deal list shows what was actually reported (as-of-sale ₪), the same way
    a real listing would, while the city/neighborhood median above it is the
    CPI-adjusted one - the two numbers answer different questions and
    shouldn't be silently mixed."""
    cpi = json.loads(CPI_FILE.read_text())
    latest_cpi_month = max(cpi)  # "YYYY-MM" sorts chronologically as a string - refreshed monthly by real_estate_fetch.py, no manual edit needed here
    cpi_latest = cpi[latest_cpi_month]
    n_total = 0
    n_kept = 0
    with open(DEALS_FILE) as f:
        for line in f:
            n_total += 1
            d = json.loads(line)
            area = d.get("assetArea")
            amount = d.get("dealAmount")
            ptype = d.get("propertyTypeDescription")
            shape = d.get("shape")
            date = d.get("dealDate")
            if not area or not amount or not shape or not date:
                continue
            if area <= 0 or amount <= 0:
                continue
            # Land/farm types are still yielded now (see PLOT_TYPES below) so
            # they show up in the deals list, just never in the price/sqm
            # stats - land ₪/sqm isn't comparable to built-property ₪/sqm.
            in_stats = ptype not in STATS_EXCLUDE_TYPES
            adj = None
            if in_stats:
                price_sqm_raw = amount / area
                if price_sqm_raw < MIN_PRICE_SQM or price_sqm_raw > MAX_PRICE_SQM:
                    continue
                ym = date[:7]
                cpi_deal = cpi.get(ym)
                if not cpi_deal:
                    continue
                adj = price_sqm_raw * (cpi_latest / cpi_deal)
            cen = polygon_centroid_3857(shape)
            if not cen:
                continue
            n_kept += 1
            raw = {
                "dt": date[:10],
                "amt": round(amount),
                "area": area,
                "st": d.get("streetNameHeb"),
                "hn": d.get("houseNum"),
                "g": d.get("gushNum"),
                "p": d.get("parcelNum"),
                "sp": d.get("subParcelNum"),
                "pt": ptype,
            }
            if ptype in PLOT_TYPES:
                pa = plot_area_sqm(shape, d.get("polygonId"), transformer)
                # Sanity floor: a plot can't be smaller than what's built on
                # it. When it is, the polygon usually isn't really this
                # deal's own plot (e.g. a shared access/common-area parcel
                # picked up instead, seen in some newer developments) -
                # better to omit than ship a number known to be wrong.
                if pa and pa >= area:
                    raw["pa"] = round(pa)
            yield cen[0], cen[1], adj, raw
    log(f"deals: total={n_total} kept={n_kept}")


def median(vals):
    s = sorted(vals)
    n = len(s)
    mid = n // 2
    return s[mid] if n % 2 else (s[mid - 1] + s[mid]) / 2


def build():
    import numpy as np
    from pyproj import Transformer
    from shapely.geometry import Point
    from shapely.strtree import STRtree

    log("loading city boundaries...")
    munis_all = load_muni_geoms()
    munis_all = {k: v for k, v in munis_all.items() if not k.startswith("ללא שיפוט")}
    names, shapes, tree = city_index(munis_all)
    munis = {k: v for k, v in munis_all.items() if v[2] != "מועצה אזורית"}
    log(f"{len(munis)} cities (regional councils excluded)")

    log("loading neighborhood boundaries...")
    nb_list = neighborhood_geoms(names, shapes, tree)  # (city, name, shapely geom, approx)
    nb_shapes = [g for _c, _n, g, _a in nb_list]
    nb_tree = STRtree(nb_shapes)

    transformer = Transformer.from_crs("EPSG:3857", "EPSG:2039", always_xy=True)

    log("loading + reprojecting deals...")
    xs, ys, prices, raws = [], [], [], []
    for x, y, price, raw in load_deals(transformer):
        xs.append(x)
        ys.append(y)
        prices.append(price)  # None for STATS_EXCLUDE_TYPES (land/farm) - still assigned/listed below, just not statted
        raws.append(raw)
    xs = np.array(xs)
    ys = np.array(ys)
    log(f"{len(prices)} deals to assign")

    itm_x, itm_y = transformer.transform(xs, ys)

    log("assigning each deal to a city + neighborhood...")
    by_city = {}
    by_nb = {}
    deals_by_city = {}  # city -> [raw dict, tagged with its own "nb" name]
    t0 = time.time()
    for i in range(len(prices)):
        pt = Point(itm_x[i], itm_y[i])
        city = find_city(pt, names, shapes, tree)
        if city is None or city not in munis:
            continue
        if prices[i] is not None:
            by_city.setdefault(city, []).append(prices[i])

        nb_name = None
        for j in nb_tree.query(pt):
            g = nb_shapes[j]
            if g.contains(pt):
                nb_city, nb_name_candidate, _g, _approx = nb_list[j]
                if nb_city == city:
                    nb_name = nb_name_candidate
                    if prices[i] is not None:
                        key = f"{city}::{nb_name}"
                        by_nb.setdefault(key, []).append(prices[i])
                break

        rec = dict(raws[i])
        if nb_name:
            rec["nb"] = nb_name
        deals_by_city.setdefault(city, []).append(rec)

        if (i + 1) % 50000 == 0:
            elapsed = time.time() - t0
            log(f"  {i+1}/{len(prices)} deals assigned, {elapsed:.0f}s elapsed")
    log(f"assignment done in {time.time()-t0:.0f}s")

    # Every city/neighborhood with at least one priced deal is included -
    # median/mean are only added once the sample is large enough to be a
    # reliable statistic (MIN_SAMPLES_*). Below that, the entry still carries
    # "n" and still gets a deal file (see write_deal_files) and a roster/board
    # entry - the individual reported prices are real data even when there
    # aren't enough of them for a trustworthy median/mean.
    city_out = {}
    for city, vals in by_city.items():
        entry = {"n": len(vals)}
        if len(vals) >= MIN_SAMPLES_CITY:
            entry["medianPricePerSqm"] = round(median(vals))
            entry["meanPricePerSqm"] = round(sum(vals) / len(vals))
        city_out[city] = entry

    nb_out = {}
    for key, vals in by_nb.items():
        entry = {"n": len(vals)}
        if len(vals) >= MIN_SAMPLES_NB:
            entry["medianPricePerSqm"] = round(median(vals))
            entry["meanPricePerSqm"] = round(sum(vals) / len(vals))
        nb_out[key] = entry

    n_city_with_median = sum(1 for e in city_out.values() if "medianPricePerSqm" in e)
    n_nb_with_median = sum(1 for e in nb_out.values() if "medianPricePerSqm" in e)
    log(f"{len(city_out)} cities ({n_city_with_median} with median), "
        f"{len(nb_out)} neighborhoods ({n_nb_with_median} with median)")
    mark_shared_plots(deals_by_city)
    write_deal_files(deals_by_city, city_out)
    write_street_index(deals_by_city, city_out)
    earliest_dt = min(r["dt"] for records in deals_by_city.values() for r in records)
    latest_cpi_month = max(json.loads(CPI_FILE.read_text()))
    return city_out, nb_out, earliest_dt, latest_cpi_month


def mark_shared_plots(deals_by_city):
    """Adds "pu" (plot units) to every PLOT_TYPES deal ("pa" present) whose
    גוש/חלקה is shared with other registered sub-parcels (e.g. the two halves
    of a semi-detached קוטג' דו משפחתי, or the many units of a "בנין") - a
    lower bound, since it only counts sub-parcels that appear somewhere in
    this same nationwide deal set, not the true unit count on that parcel.
    Omitted (implying a single, non-shared unit) when only one sub-parcel is
    known - which for a קוטג' דו משפחתי may just mean its other half never
    sold in the tracked period, not that the plot definitely isn't shared."""
    parcel_subunits = {}
    for records in deals_by_city.values():
        for r in records:
            if r.get("g") is None or r.get("p") is None:
                continue
            parcel_subunits.setdefault((r["g"], r["p"]), set()).add(r.get("sp"))
    for records in deals_by_city.values():
        for r in records:
            if "pa" not in r:
                continue
            units = parcel_subunits.get((r.get("g"), r.get("p")))
            if units and len(units) > 1:
                r["pu"] = len(units)


def write_deal_files(deals_by_city, city_out):
    """One plain (non-JS-module) JSON array per city under assets/deals/ -
    fetched lazily client-side only for a city the visitor actually picks to
    compare, the same lazy-per-city-asset pattern canopy-map.html's own
    heat/canopy blob PNGs already use (assets/blobs/{heat,canopy}/<city>.png),
    rather than shipping every city's individual deals in the JS bundle up
    front. Only written for cities that made it into city_out (>= min
    samples) - no page ever links to a deal file for a city that isn't shown
    on the map/board in the first place."""
    DEALS_OUT_DIR.mkdir(parents=True, exist_ok=True)
    n_written = 0
    total_kb = 0.0
    for city, records in deals_by_city.items():
        if city not in city_out:
            continue
        records.sort(key=lambda r: r["dt"], reverse=True)
        out_path = DEALS_OUT_DIR / f"{city}.json"
        out_path.write_text(json.dumps(records, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
        total_kb += out_path.stat().st_size / 1024
        n_written += 1
    log(f"wrote {n_written} per-city deal files under assets/deals/ ({total_kb:.0f} KB total)")


def write_street_index(deals_by_city, city_out):
    """A single small, EAGERLY-loaded nationwide index - [{"s":street,
    "c":city}, ...], names only, no deal records - unlike assets/deals/
    above, which is per-city and lazy (a full city's deals can be a few MB,
    too much to ship for all 142 cities up front). Street names alone are
    small enough (a few thousand distinct (city, street) pairs nationwide)
    to ship as one file, which is what lets the street-level compare
    picker search "every street in the country" directly instead of
    requiring a city to be picked first."""
    stamp = time.strftime("%Y-%m-%dT%H:%M%z") or time.strftime("%Y-%m-%dT%H:%M")
    index = []
    for city, records in deals_by_city.items():
        if city not in city_out:
            continue
        for s in sorted({r["st"] for r in records if r.get("st")}):
            index.append({"s": s, "c": city})
    write_js("STREET_INDEX", index, SRC / "real-estate-streets.js",
              f"Nationwide street-name index (names only, no deal records), computed {stamp} - "
              f"used for the street-level compare picker's national search.")


def main():
    stamp = time.strftime("%Y-%m-%dT%H:%M%z") or time.strftime("%Y-%m-%dT%H:%M")
    city_out, nb_out, earliest_dt, latest_cpi_month = build()
    write_js("CITY_REAL_ESTATE", city_out, SRC / "real-estate-cities.js",
              f"City-level median/mean CPI-adjusted price per m2, computed {stamp} "
              f"(deals since {earliest_dt}, CPI-adjusted to {latest_cpi_month}, GovMap real-estate API)")
    write_js("NEIGHBORHOOD_REAL_ESTATE", nb_out, SRC / "real-estate-neighborhoods.js",
              f"Neighborhood-level median/mean CPI-adjusted price per m2, computed {stamp} "
              f"(deals since {earliest_dt}, CPI-adjusted to {latest_cpi_month}, GovMap real-estate API)")


if __name__ == "__main__":
    main()
