#!/usr/bin/env python3
"""
Builds the real-estate price/m² comparison data: city / neighborhood median
CPI-adjusted price per square meter, from the local (gitignored) raw deal
dump already fetched from GovMap's real-estate API (zip/real_estate_deals_raw.jsonl,
~285k deals nationwide since 2021-08) plus the same municipal/OSM-neighborhood
boundaries canopy_build.py already resolved (zip/muni_il.json, zip/osm_neighborhoods_raw.json,
zip/osm_neighborhood_points.json) - reuses load_muni_geoms()/city_index()/
find_city()/neighborhood_geoms() as-is, no new boundary geometry.

Each deal is assigned to a city/neighborhood by point-in-polygon on its own
centroid (same simplification canopy_build.py uses for tree canopy - a deal's
polygon is a single building footprint, tiny next to a city/neighborhood, so
centroid vs. true-intersection makes no practical difference here).

Usage:
    python3 tools/real_estate_build.py
"""
import json
import re
import sys
import time
from pathlib import Path

from osgeo import ogr
ogr.UseExceptions()

sys.path.insert(0, str(Path(__file__).resolve().parent))
from canopy_build import load_muni_geoms, city_index, find_city, neighborhood_geoms

ROOT = Path(__file__).resolve().parent.parent
ZIP = ROOT / "zip"
SRC = ROOT / "src"

DEALS_FILE = ZIP / "real_estate_deals_raw.jsonl"
CPI_FILE = ZIP / "cpi_table.json"
LATEST_CPI_MONTH = "2026-06"
EXCLUDE_TYPES = {"קרקע", "מגרש", "משק חקלאי", "משק עזר"}
MIN_PRICE_SQM = 2000
MAX_PRICE_SQM = 150000
MIN_SAMPLES_CITY = 5
MIN_SAMPLES_NB = 5

CENTROID_RE = re.compile(r"(-?\d+\.?\d*)\s+(-?\d+\.?\d*)")


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def write_js(varname, data, out_path, header_comment):
    out_path.write_text(
        f"// {header_comment}\n"
        f"// Generated by tools/real_estate_build.py - do not edit by hand.\n"
        f"export const {varname} = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    kb = out_path.stat().st_size / 1024
    log(f"wrote {out_path.relative_to(ROOT)} ({kb:.1f} KB)")


def polygon_centroid_3857(shape):
    inner = shape.split("(((")[1].split(")))")[0]
    pts = CENTROID_RE.findall(inner)
    if not pts:
        return None
    xs = [float(p[0]) for p in pts]
    ys = [float(p[1]) for p in pts]
    return sum(xs) / len(xs), sum(ys) / len(ys)


def load_deals():
    """Yields (x_3857, y_3857, adj_price_per_sqm) for every deal that passes
    the same filters build_heatmap.py (the earlier national-heatmap pass)
    used, so the two views stay numerically consistent."""
    cpi = json.loads(CPI_FILE.read_text())
    cpi_latest = cpi[LATEST_CPI_MONTH]
    n_total = 0
    n_kept = 0
    with open(DEALS_FILE) as f:
        for line in f:
            n_total += 1
            d = json.loads(line)
            area = d.get("assetArea")
            amount = d.get("dealAmount")
            ptype = d.get("propertyTypeDescription")
            shape = d.get("shape")
            date = d.get("dealDate")
            if not area or not amount or not shape or not date:
                continue
            if area <= 0 or amount <= 0:
                continue
            if ptype in EXCLUDE_TYPES:
                continue
            price_sqm_raw = amount / area
            if price_sqm_raw < MIN_PRICE_SQM or price_sqm_raw > MAX_PRICE_SQM:
                continue
            ym = date[:7]
            cpi_deal = cpi.get(ym)
            if not cpi_deal:
                continue
            adj = price_sqm_raw * (cpi_latest / cpi_deal)
            cen = polygon_centroid_3857(shape)
            if not cen:
                continue
            n_kept += 1
            yield cen[0], cen[1], adj
    log(f"deals: total={n_total} kept={n_kept}")


def median(vals):
    s = sorted(vals)
    n = len(s)
    mid = n // 2
    return s[mid] if n % 2 else (s[mid - 1] + s[mid]) / 2


def build():
    import numpy as np
    from pyproj import Transformer
    from shapely.geometry import Point
    from shapely.strtree import STRtree

    log("loading city boundaries...")
    munis_all = load_muni_geoms()
    munis_all = {k: v for k, v in munis_all.items() if not k.startswith("ללא שיפוט")}
    names, shapes, tree = city_index(munis_all)
    munis = {k: v for k, v in munis_all.items() if v[2] != "מועצה אזורית"}
    log(f"{len(munis)} cities (regional councils excluded)")

    log("loading neighborhood boundaries...")
    nb_list = neighborhood_geoms(names, shapes, tree)  # (city, name, shapely geom, approx)
    nb_shapes = [g for _c, _n, g, _a in nb_list]
    nb_tree = STRtree(nb_shapes)

    log("loading + reprojecting deals...")
    xs, ys, prices = [], [], []
    for x, y, price in load_deals():
        xs.append(x)
        ys.append(y)
        prices.append(price)
    xs = np.array(xs)
    ys = np.array(ys)
    prices = np.array(prices)
    log(f"{len(prices)} priced deals to assign")

    transformer = Transformer.from_crs("EPSG:3857", "EPSG:2039", always_xy=True)
    itm_x, itm_y = transformer.transform(xs, ys)

    log("assigning each deal to a city + neighborhood...")
    by_city = {}
    by_nb = {}
    t0 = time.time()
    for i in range(len(prices)):
        pt = Point(itm_x[i], itm_y[i])
        city = find_city(pt, names, shapes, tree)
        if city is None or city not in munis:
            continue
        by_city.setdefault(city, []).append(prices[i])

        for j in nb_tree.query(pt):
            g = nb_shapes[j]
            if g.contains(pt):
                nb_city, nb_name, _g, _approx = nb_list[j]
                if nb_city == city:
                    key = f"{city}::{nb_name}"
                    by_nb.setdefault(key, []).append(prices[i])
                break
        if (i + 1) % 50000 == 0:
            elapsed = time.time() - t0
            log(f"  {i+1}/{len(prices)} deals assigned, {elapsed:.0f}s elapsed")
    log(f"assignment done in {time.time()-t0:.0f}s")

    city_out = {}
    for city, vals in by_city.items():
        if len(vals) < MIN_SAMPLES_CITY:
            continue
        city_out[city] = {
            "medianPricePerSqm": round(median(vals)),
            "meanPricePerSqm": round(sum(vals) / len(vals)),
            "n": len(vals),
        }

    nb_out = {}
    for key, vals in by_nb.items():
        if len(vals) < MIN_SAMPLES_NB:
            continue
        nb_out[key] = {
            "medianPricePerSqm": round(median(vals)),
            "meanPricePerSqm": round(sum(vals) / len(vals)),
            "n": len(vals),
        }

    log(f"{len(city_out)} cities, {len(nb_out)} neighborhoods with >= min samples")
    return city_out, nb_out


def main():
    stamp = time.strftime("%Y-%m-%dT%H:%M%z") or time.strftime("%Y-%m-%dT%H:%M")
    city_out, nb_out = build()
    write_js("CITY_REAL_ESTATE", city_out, SRC / "real-estate-cities.js",
              f"City-level median/mean CPI-adjusted price per m2, computed {stamp} "
              f"(deals since 2021-08, CPI-adjusted to {LATEST_CPI_MONTH}, GovMap real-estate API)")
    write_js("NEIGHBORHOOD_REAL_ESTATE", nb_out, SRC / "real-estate-neighborhoods.js",
              f"Neighborhood-level median/mean CPI-adjusted price per m2, computed {stamp} "
              f"(deals since 2021-08, CPI-adjusted to {LATEST_CPI_MONTH}, GovMap real-estate API)")


if __name__ == "__main__":
    main()
