/**
 * Per-year config for the audited local-authority financial reports
 * (משרד הפנים, published on data.gov.il / CKAN DataStore). GENERATED BY HAND
 * from direct probing, not documentation - none of this is documented.
 *
 * Two source CKAN packages, with genuinely different schemas per year - not
 * a guess, confirmed by fetching real sample rows from each resource:
 *   - "local-authorities" (all authority types: cities/local councils/
 *     regional councils) - one resource per year, 2018/2019/2022/2023/2024.
 *     sheet field is spelled 'גיליון' for 2018/2019/2022, but 'גליון' (no
 *     extra י) for 2023/2024 - the ministry's own export changed spelling.
 *   - "local-council-1" (local councils ONLY) - fills years
 *     local-authorities doesn't cover: 2016, 2017 (via a resource spanning
 *     2017-2018 together - needs its own year filter), 2020, 2021.
 * 2014-2015 are NOT included: those two years are split into 2-3 files per
 * year by alphabetical range of the authority's name, which this page
 * doesn't yet handle.
 *
 * Only 2023 and 2024 carry the ministry's own computed summary sheet
 * ("דוח לתושב" - a residents'-facing rollup with ready-made lines like
 * "סהכ הכנסות"/"סהכ הוצאות"). Confirmed absent from every earlier year
 * checked (2016, 2018, 2019, 2020, 2021, 2022), so no *national* KPI is
 * attempted for years before 2023 - that would need summing every
 * authority's figure for a year, and there is no ready-made per-authority
 * total to sum in those years.
 *
 * Form 2 ("טופס 2") is a different story: it DOES carry a stable
 * receipts/payments/surplus total in every year, just under two different
 * labels depending on era - confirmed directly, not assumed, by checking a
 * real authority in each year (see FORM2_TOTALS below). This is what
 * powers the per-authority revenue/expense-over-the-years chart: unlike the
 * national KPIs, this is one authority's own figure per year, no cross-
 * authority summing needed, so both eras are usable.
 */
export const YEAR_RESOURCES = {
  2016: { source: 'local-council-1', resourceId: 'b7a3042a-a49a-4b38-99da-1de2fa9619ca', sheetField: 'גיליון', hasSummary: false, coverage: 'מועצות מקומיות בלבד' },
  2017: { source: 'local-council-1', resourceId: '501c4ea2-cb2e-48e7-8de4-74c038de3449', sheetField: 'גיליון', yearFilter: { field: 'שנת_הדוח', value: '2017' }, hasSummary: false, coverage: 'מועצות מקומיות בלבד' },
  2018: { source: 'local-authorities', resourceId: '1618b871-9b3d-4bc5-acc0-c1fbe939a3b1', sheetField: 'גיליון', hasSummary: false, coverage: 'כלל סוגי הרשויות' },
  2019: { source: 'local-authorities', resourceId: 'f3f39a40-8404-4179-bcee-616ab2433631', sheetField: 'גיליון', hasSummary: false, coverage: 'כלל סוגי הרשויות' },
  2020: { source: 'local-council-1', resourceId: 'f2f0d291-2d4c-43dc-a3ab-a884625e9f9a', sheetField: 'גיליון', hasSummary: false, coverage: 'מועצות מקומיות בלבד' },
  2021: { source: 'local-council-1', resourceId: 'a001d2a7-f941-4ea9-beab-8065f549994f', sheetField: 'גיליון', hasSummary: false, coverage: 'מועצות מקומיות בלבד' },
  2022: { source: 'local-authorities', resourceId: 'e5ff9ad0-6db2-4660-a94e-4499fce9475d', sheetField: 'גיליון', hasSummary: false, coverage: 'כלל סוגי הרשויות' },
  2023: { source: 'local-authorities', resourceId: '5825080f-905c-40f7-9f53-8ea1cf8ed394', sheetField: 'גליון', hasSummary: true, coverage: 'כלל סוגי הרשויות' },
  2024: { source: 'local-authorities', resourceId: '6e153ddd-d4d4-4450-a78c-20f594a7986a', sheetField: 'גליון', hasSummary: true, coverage: 'כלל סוגי הרשויות' },
};

// Newest first - how the year <select> lists them.
export const YEARS_DESC = Object.keys(YEAR_RESOURCES).map(Number).sort((a, b) => b - a);

// The single sheet+row+column combo that yields exactly one row per
// authority, cheaply, for the name roster (259 authorities, one page).
export const ROSTER_YEAR = 2024;
export const ROSTER_FILTERS = { גליון: 'נתונים לטופס 1', שורה: 'יתרה לתחילת שנה', עמודה: 'שנה נוכחית' };

// The residents'-report ("דוח לתושב") rows that carry the ministry's own
// computed bottom-line totals, for the years that have this sheet at all.
export const SUMMARY_SHEET = 'דוח לתושב';
// Labels copied verbatim from the actual data - the source spells these
// without gershayim ('סהכ', not 'סה"כ'), confirmed against real rows before
// writing this, not the grammatically "correct" spelling.
export const SUMMARY_ROWS = {
  revenue: 'סהכ הכנסות',
  expense: 'סהכ הוצאות',
  surplus: 'עודף (גרעון) השנה בתקציב הרגיל',
  ownRevenue: 'הכנסות עצמיות',
  grants: 'מענקים',
};
// Column that means "what actually happened this year" - not the budgeted
// plan and not last year's figures, which the same sheet also carries.
export const SUMMARY_COLUMN = 'ביצוע שנה נוכחית';

/**
 * Form 2's own receipts/payments/surplus totals, confirmed present in every
 * one of the 9 years this page covers (checked directly per year: a real
 * council in 2016/2017/2020/2021's local-council-1 resource, a real
 * authority in 2018/2019/2022/2023/2024's local-authorities resource) - just
 * spelled two different ways depending on era. 2023/2024 introduced a
 * "פעולות רגילות" (regular operations, as opposed to emergency/פעולות חירום)
 * prefix and dropped the gershayim from "סה"כ"; 2016-2022 has neither.
 */
export const FORM2_ROWS_BY_ERA = {
  legacy: { revenue: 'סה"כ תקבולים', expense: 'סה"כ תשלומים' }, // 2016-2022
  current: { revenue: 'פעולות רגילות - סהכ תקבולים', expense: 'פעולות רגילות - סהכ תשלומים' }, // 2023-2024
};
export const form2RowsFor = (year) => (YEAR_RESOURCES[year].hasSummary
  ? FORM2_ROWS_BY_ERA.current : FORM2_ROWS_BY_ERA.legacy);
